name: Generate Service Worker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Generate Service Worker
        run: node ./extra/generate-sw.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push changes
        run: |
          git config user.name jonnypaes
          git config user.email jonny.paes@gmail.com
          git add service-worker.js
          git commit -m "Generated service-worker.js with latest commit hash" || echo "No changes to commit"
          git push
